Avatar and Badge
SatwikaKacham/component-library pull request #1
Opened 2022-01-28 19:56 UTC by SatwikaKacham

2022-01-29 05:27 UTC, kart-c requested changes

2022-01-29 05:27 UTC, kart-c commented on badge/badge.css
> +}
instead of hard-coding colors you can use variables

2022-01-29 05:27 UTC, kart-c commented on avatar/avatar.css
> +    /* color:rgb(231, 231, 231); */
you can remove this comment if it is not required

2022-01-30 09:20 UTC, kart-c approved these changes
Approved

2022-01-30 09:20 UTC, mohammed-sas approved these changes
you are good to merge

2022-01-30 09:30 UTC, merged